net2720/ilove-refactor

src/pages/Post.tsx, src/pages/SignUp.tsx, src/services/Fetcher.ts, src/utils.tsx
Instance 함수 및 회원가입 페이지 주소검색 추가
=> Instance 함수 및 회원가입 페이지 주소검색 추가

src/pages/HospitalInfo.tsx, src/services/Fetcher.ts
feat / HospitalInfo Page API 연동 관련 커밋입니다.
=> feat / HospitalInfo Page API 연동 관련 커밋입니다.

package.json, src/constants/Border.ts, src/pages/Login.tsx, src/pages/Post.tsx, src/services/Fetcher.ts, src/utils.tsx
=> 로그인 및 회원가입 기능 구현완료

package.json, src/pages/Home.tsx, src/pages/HospitalInfo.tsx, src/services/Fetcher.ts
feat / hospitalInfo 페이지 연동 관련 커밋입니다.
=> feat / hospitalInfo 페이지 연동 관련 커밋입니다.

src/services/Fetcher.ts
!HOTFIX / 서버 API 통신 에러 관련 핫픽스 커밋입니다.
=> !HOTFIX / 서버 API 통신 에러 관련 핫픽스 커밋입니다.

package.json
!HOTFIX / package.json 누락 관련 커밋입니다.
=> !HOTFIX / package.json 누락 관련 커밋입니다.

package.json, src/services/Fetcher.ts
!HOTFIX / 배포 문제 해결 관련 원복 커밋입니다.
=> !HOTFIX / 배포 문제 해결 관련 원복 커밋입니다.

package.json, src/services/Fetcher.ts
!HOTFIX / 내부 배포 서버 Axios 에러 관련 핫픽스 커밋입니다.
=> !HOTFIX / 내부 배포 서버 Axios 에러 관련 핫픽스 커밋입니다.

package.json, src/components/BasicButton.tsx, src/components/Index.ts, src/components/NavigationBar.tsx, src/pages/Home.tsx, src/pages/HospitalInfo.tsx, src/pages/MyPage.tsx, src/services/Fetcher.ts
feat / 주소 스키마 변경 관련 재배포 커밋입니다.
=> feat / 주소 스키마 변경 관련 재배포 커밋입니다.

package.json, src/services/Fetcher.ts
=> !HOTFIX / 프록시 주소 누락 관련 커밋입니다.

src/components/BasicButton.tsx, src/components/Index.ts, src/components/Modal.tsx, src/components/MyPageModal.tsx, src/components/NavigationBar.tsx, src/components/styles/ModalStyle.tsx, src/pages/Home.tsx, src/pages/MyPage.tsx
=> feat / 마이페이지 API 연동 관련 커밋입니다.

package-lock.json, package.json, public/index.html, src/App.tsx, src/components/NavigationBar.tsx, src/components/SearchBar.tsx, src/pages/SearchHp.tsx, src/recoil/atoms.tsx, src/utils.tsx, tsconfig.json
=> 카카오 지도 및 내 위치 마커 기능 구현.

src/pages/MyPage.tsx
feat / 주소 정보 수정 API 연동 완료 커밋입니다.
=> feat / 주소 정보 수정 API 연동 완료 커밋입니다.

src/App.tsx, src/components/BasicButton.tsx, src/components/Modal.tsx, src/components/MyPageModal.tsx, src/components/NavigationBar.tsx, src/pages/Home.tsx, src/pages/HospitalInfo.tsx, src/pages/Login.tsx, src/pages/MyPage.tsx, src/services/Fetcher.ts, src/utils.tsx
fix / 로그인 및 로그아웃 후 마이페이지 이동 시 예전 토큰 적용 관련 버그 수정 커밋입니다.
=> fix / 로그인 및 로그아웃 후 마이페이지 이동 시 예전 토큰 적용 관련 버그 수정 커밋입니다.

src/App.tsx, src/components/BasicButton.tsx, src/components/Modal.tsx, src/components/MyPageModal.tsx, src/components/NavigationBar.tsx, src/pages/Home.tsx, src/pages/HospitalInfo.tsx, src/pages/Login.tsx, src/pages/MyPage.tsx, src/services/Fetcher.ts, src/utils.tsx
더 좋은 해결책이 발견되어 커밋 Revert 하겠습니다.
=> Revert "fix / 로그인 및 로그아웃 후 마이페이지 이동 시 예전 토큰 적용 관련 버그 수정 커밋입니다."

.vscode/settings.json, src/components/BasicButton.tsx, src/components/Modal.tsx, src/components/styles/ModalStyle.tsx, src/constants/Colors.ts
fix / mypage modal창 CSS 수정 커밋입니다.
=> fix / mypage modal창 CSS 수정 커밋입니다.

.vscode/settings.json
=> !HOTFIX / 린트 속성 동기화 관련 커밋입니다.

package-lock.json, package.json, src/components/SearchBar.tsx, src/pages/HpList/MyComponent.tsx, src/pages/SearchHp.tsx, src/recoil/atoms.tsx
=> 가상 스크롤 빈배열 초기화 버그 수정 

public/index.html
!HOTFIX / 지도 API 인증 오류 관련 수정 커밋입니다.
=> !HOTFIX / 지도 API 인증 오류 관련 수정 커밋입니다.

src/App.tsx, src/pages/HospitalInfo.tsx, src/pages/HpList/MyComponent.tsx, src/pages/HpList/VirtualScroll.tsx, src/pages/MyPage.tsx, src/pages/SearchHp.tsx, src/pages/useGeolocation.tsx, src/utils.tsx
병원 찾기 페이지 비회원 접속 시 현재 본인 위치로 지도 수정,
마이페이지에서 주소 변경 시 병원찾기에 회원 정보 안바뀌는 오류 수정
=> 병원 찾기 페이지 기능 변경 및 마이페이지 css 수정
